from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import datetime
from PyQt5.QtCore import QDateTime, QTimer
from PyQt5.QtGui import QTransform
from PyQt5.QtWidgets import QApplication
from numpy import random
from PyQt5 import QtCore, QtGui, QtWidgets
import dronekit
from dronekit import connect, VehicleMode, LocationGlobal, LocationGlobalRelative, Command ,Vehicle
import time
import math
from pymavlink import mavutil
import numpy

vehicle = connect('127.0.0.1:14550', wait_ready=True)
class Ui_Form(QtWidgets.QMainWindow):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1694, 987)
        Form.setStyleSheet("\n"
"background-color: rgb(136, 138, 133);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(900, 80, 751, 891))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/home/ege/Pictures/uçuş_alanı_düzeltilmiş.png")) #1
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(1000, 520, 16, 21))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png")) #1
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 290, 141, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.uav_connect)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 320, 141, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.otonom_mode)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 350, 141, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.manuel_mode)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(1000, 580, 16, 21))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(1000, 550, 16, 21))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(1000, 620, 21, 31))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("/home/ege/Downloads/uav_bizim2.png"))
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(1000, 490, 20, 21))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_6.setObjectName("label_6")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 141, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(160, 30, 143, 251))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 390, 161, 571))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_59 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_3.addWidget(self.label_59)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_3.addWidget(self.label_22)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_3.addWidget(self.label_20)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_3.addWidget(self.label_19)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_3.addWidget(self.label_18)
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_3.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_3.addWidget(self.label_31)
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_3.addWidget(self.label_29)
        self.label_35 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_3.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_3.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_3.addWidget(self.label_37)
        self.label_34 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_3.addWidget(self.label_34)
        self.label_32 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_3.addWidget(self.label_32)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_3.addWidget(self.label_23)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        self.label_95 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_95.setObjectName("label_95")
        self.verticalLayout_3.addWidget(self.label_95)
        self.label_96 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_96.setObjectName("label_96")
        self.verticalLayout_3.addWidget(self.label_96)
        self.label_97 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_97.setObjectName("label_97")
        self.verticalLayout_3.addWidget(self.label_97)
        self.label_98 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_98.setObjectName("label_98")
        self.verticalLayout_3.addWidget(self.label_98)
        self.label_99 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_99.setObjectName("label_99")
        self.verticalLayout_3.addWidget(self.label_99)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 320, 141, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.FBWA_mode) #1
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(160, 350, 141, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.Loiter_mode)#1
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(500, 30, 161, 251))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_49 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_5.addWidget(self.label_49)
        self.label_50 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_5.addWidget(self.label_50)
        self.label_51 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_5.addWidget(self.label_51)
        self.label_52 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_5.addWidget(self.label_52)
        self.label_53 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_5.addWidget(self.label_53)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(350, 30, 153, 251))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_54 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_6.addWidget(self.label_54)
        self.label_55 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_6.addWidget(self.label_55)
        self.label_56 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_6.addWidget(self.label_56)
        self.label_57 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_6.addWidget(self.label_57)
        self.label_58 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_6.addWidget(self.label_58)
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 290, 141, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.RTL_mode)#1
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(180, 390, 160, 571))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_60 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_60.setObjectName("label_60")
        self.verticalLayout_4.addWidget(self.label_60)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_4.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_4.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_4.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_4.addWidget(self.label_28)
        self.label_38 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_4.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_4.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_4.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_4.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_4.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_4.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_4.addWidget(self.label_44)
        self.label_45 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_4.addWidget(self.label_45)
        self.label_46 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_4.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_4.addWidget(self.label_47)
        self.label_48 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_4.addWidget(self.label_48)
        self.label_100 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_100.setObjectName("label_100")
        self.verticalLayout_4.addWidget(self.label_100)
        self.label_101 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_101.setObjectName("label_101")
        self.verticalLayout_4.addWidget(self.label_101)
        self.label_102 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_102.setObjectName("label_102")
        self.verticalLayout_4.addWidget(self.label_102)
        self.label_103 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_103.setObjectName("label_103")
        self.verticalLayout_4.addWidget(self.label_103)
        self.label_104 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_104.setObjectName("label_104")
        self.verticalLayout_4.addWidget(self.label_104)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(340, 390, 160, 571))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_61 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_7.addWidget(self.label_61)
        self.label_62 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_7.addWidget(self.label_62)
        self.label_63 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_7.addWidget(self.label_63)
        self.label_64 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_7.addWidget(self.label_64)
        self.label_65 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_65.setObjectName("label_65")
        self.verticalLayout_7.addWidget(self.label_65)
        self.label_66 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_66.setObjectName("label_66")
        self.verticalLayout_7.addWidget(self.label_66)
        self.label_67 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_7.addWidget(self.label_67)
        self.label_68 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_68.setObjectName("label_68")
        self.verticalLayout_7.addWidget(self.label_68)
        self.label_69 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_69.setObjectName("label_69")
        self.verticalLayout_7.addWidget(self.label_69)
        self.label_70 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_70.setObjectName("label_70")
        self.verticalLayout_7.addWidget(self.label_70)
        self.label_71 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_71.setObjectName("label_71")
        self.verticalLayout_7.addWidget(self.label_71)
        self.label_72 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_72.setObjectName("label_72")
        self.verticalLayout_7.addWidget(self.label_72)
        self.label_73 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_73.setObjectName("label_73")
        self.verticalLayout_7.addWidget(self.label_73)
        self.label_74 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_74.setObjectName("label_74")
        self.verticalLayout_7.addWidget(self.label_74)
        self.label_75 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_75.setObjectName("label_75")
        self.verticalLayout_7.addWidget(self.label_75)
        self.label_76 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_76.setObjectName("label_76")
        self.verticalLayout_7.addWidget(self.label_76)
        self.label_77 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_77.setObjectName("label_77")
        self.verticalLayout_7.addWidget(self.label_77)
        self.label_105 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_105.setObjectName("label_105")
        self.verticalLayout_7.addWidget(self.label_105)
        self.label_106 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_106.setObjectName("label_106")
        self.verticalLayout_7.addWidget(self.label_106)
        self.label_107 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_107.setObjectName("label_107")
        self.verticalLayout_7.addWidget(self.label_107)
        self.label_108 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_108.setObjectName("label_108")
        self.verticalLayout_7.addWidget(self.label_108)
        self.label_109 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_109.setObjectName("label_109")
        self.verticalLayout_7.addWidget(self.label_109)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(500, 390, 160, 571))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_78 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_78.setObjectName("label_78")
        self.verticalLayout_8.addWidget(self.label_78)
        self.label_79 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_79.setObjectName("label_79")
        self.verticalLayout_8.addWidget(self.label_79)
        self.label_80 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_80.setObjectName("label_80")
        self.verticalLayout_8.addWidget(self.label_80)
        self.label_81 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_81.setObjectName("label_81")
        self.verticalLayout_8.addWidget(self.label_81)
        self.label_82 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_82.setObjectName("label_82")
        self.verticalLayout_8.addWidget(self.label_82)
        self.label_83 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_83.setObjectName("label_83")
        self.verticalLayout_8.addWidget(self.label_83)
        self.label_84 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_8.addWidget(self.label_84)
        self.label_85 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_8.addWidget(self.label_85)
        self.label_86 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_8.addWidget(self.label_86)
        self.label_87 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_87.setObjectName("label_87")
        self.verticalLayout_8.addWidget(self.label_87)
        self.label_88 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_88.setObjectName("label_88")
        self.verticalLayout_8.addWidget(self.label_88)
        self.label_89 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_89.setObjectName("label_89")
        self.verticalLayout_8.addWidget(self.label_89)
        self.label_90 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_90.setObjectName("label_90")
        self.verticalLayout_8.addWidget(self.label_90)
        self.label_91 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_91.setObjectName("label_91")
        self.verticalLayout_8.addWidget(self.label_91)
        self.label_92 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_92.setObjectName("label_92")
        self.verticalLayout_8.addWidget(self.label_92)
        self.label_93 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_93.setObjectName("label_93")
        self.verticalLayout_8.addWidget(self.label_93)
        self.label_94 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_94.setObjectName("label_94")
        self.verticalLayout_8.addWidget(self.label_94)
        self.label_110 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_110.setObjectName("label_110")
        self.verticalLayout_8.addWidget(self.label_110)
        self.label_111 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_111.setObjectName("label_111")
        self.verticalLayout_8.addWidget(self.label_111)
        self.label_112 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_112.setObjectName("label_112")
        self.verticalLayout_8.addWidget(self.label_112)
        self.label_113 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_113.setObjectName("label_113")
        self.verticalLayout_8.addWidget(self.label_113)
        self.label_114 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_114.setObjectName("label_114")
        self.verticalLayout_8.addWidget(self.label_114)
        self.label_33 = QtWidgets.QLabel(Form)
        self.label_33.setGeometry(QtCore.QRect(1000, 430, 16, 21))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))#1
        self.label_33.setObjectName("label_33")
        self.label_115 = QtWidgets.QLabel(Form)
        self.label_115.setGeometry(QtCore.QRect(1000, 460, 16, 21))
        self.label_115.setText("")
        self.label_115.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_115.setObjectName("label_115")
        self.label_116 = QtWidgets.QLabel(Form)
        self.label_116.setGeometry(QtCore.QRect(1000, 380, 20, 21))
        self.label_116.setText("")
        self.label_116.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_116.setObjectName("label_116")
        self.label_117 = QtWidgets.QLabel(Form)
        self.label_117.setGeometry(QtCore.QRect(1000, 400, 16, 21))
        self.label_117.setText("")
        self.label_117.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_117.setObjectName("label_117")
        self.label_118 = QtWidgets.QLabel(Form)
        self.label_118.setGeometry(QtCore.QRect(1030, 400, 16, 21))
        self.label_118.setText("")
        self.label_118.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_118.setObjectName("label_118")
        self.label_119 = QtWidgets.QLabel(Form)
        self.label_119.setGeometry(QtCore.QRect(1030, 550, 16, 21))
        self.label_119.setText("")
        self.label_119.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_119.setObjectName("label_119")
        self.label_120 = QtWidgets.QLabel(Form)
        self.label_120.setGeometry(QtCore.QRect(1030, 460, 16, 21))
        self.label_120.setText("")
        self.label_120.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_120.setObjectName("label_120")
        self.label_121 = QtWidgets.QLabel(Form)
        self.label_121.setGeometry(QtCore.QRect(1030, 380, 20, 21))
        self.label_121.setText("")
        self.label_121.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_121.setObjectName("label_121")
        self.label_122 = QtWidgets.QLabel(Form)
        self.label_122.setGeometry(QtCore.QRect(1030, 580, 16, 21))
        self.label_122.setText("")
        self.label_122.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_122.setObjectName("label_122")
        self.label_123 = QtWidgets.QLabel(Form)
        self.label_123.setGeometry(QtCore.QRect(1030, 430, 16, 21))
        self.label_123.setText("")
        self.label_123.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_123.setObjectName("label_123")
        self.label_124 = QtWidgets.QLabel(Form)
        self.label_124.setGeometry(QtCore.QRect(1030, 490, 20, 21))
        self.label_124.setText("")
        self.label_124.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_124.setObjectName("label_124")
        self.label_125 = QtWidgets.QLabel(Form)
        self.label_125.setGeometry(QtCore.QRect(1030, 520, 16, 21))
        self.label_125.setText("")
        self.label_125.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_125.setObjectName("label_125")
        self.label_126 = QtWidgets.QLabel(Form)
        self.label_126.setGeometry(QtCore.QRect(1000, 330, 16, 21))
        self.label_126.setText("")
        self.label_126.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_126.setObjectName("label_126")
        self.label_127 = QtWidgets.QLabel(Form)
        self.label_127.setGeometry(QtCore.QRect(1030, 330, 16, 21))
        self.label_127.setText("")
        self.label_127.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_127.setObjectName("label_127")
        self.label_128 = QtWidgets.QLabel(Form)
        self.label_128.setGeometry(QtCore.QRect(1000, 360, 16, 21))
        self.label_128.setText("")
        self.label_128.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_128.setObjectName("label_128")
        self.label_129 = QtWidgets.QLabel(Form)
        self.label_129.setGeometry(QtCore.QRect(1030, 360, 16, 21))
        self.label_129.setText("")
        self.label_129.setPixmap(QtGui.QPixmap("/home/ege/Downloads/airliner.png"))
        self.label_129.setObjectName("label_129")
        self.label_130 = QtWidgets.QLabel(Form)
        self.label_130.setGeometry(QtCore.QRect(1080, 460, 21, 21))
        self.label_130.setText("")
        self.label_130.setPixmap(QtGui.QPixmap("/home/ege/Downloads/qr.png"))
        self.label_130.setObjectName("label_130")
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.label_6.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.label_4.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.verticalLayoutWidget_5.raise_()
        self.verticalLayoutWidget_6.raise_()
        self.pushButton_6.raise_()
        self.verticalLayoutWidget_4.raise_()
        self.verticalLayoutWidget_7.raise_()
        self.verticalLayoutWidget_8.raise_()
        self.label_33.raise_()
        self.label_115.raise_()
        self.label_116.raise_()
        self.label_117.raise_()
        self.label_118.raise_()
        self.label_119.raise_()
        self.label_120.raise_()
        self.label_121.raise_()
        self.label_122.raise_()
        self.label_123.raise_()
        self.label_124.raise_()
        self.label_125.raise_()
        self.label_126.raise_()
        self.label_127.raise_()
        self.label_128.raise_()
        self.label_129.raise_()
        self.label_130.raise_()
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Connect Vehicle"))
        self.pushButton_2.setText(_translate("Form", "Otonom Mode"))
        self.pushButton_3.setText(_translate("Form", "Manuel Mode"))
        self.label_9.setText(_translate("Form", "iHA ENLEM:"))
        self.label_7.setText(_translate("Form", "İHA BOYLAM:"))
        self.label_11.setText(_translate("Form", "İHA YÜKSEKLİK:"))
        self.label_10.setText(_translate("Form", "İHA HIZ :"))
        self.label_8.setText(_translate("Form", "İHA MODE :"))
        self.label_14.setText(_translate("Form", "TextLabel_enlem"))
        self.label_15.setText(_translate("Form", "TextLabel_boylam"))
        self.label_16.setText(_translate("Form", "TextLabel_yüksekllik"))
        self.label_13.setText(_translate("Form", "TextLabel_hız"))
        self.label_12.setText(_translate("Form", "TextLabel_mode"))
        self.label_59.setText(_translate("Form", "DURUM"))
        self.label_22.setText(_translate("Form", "SAFDER DURUM"))
        self.label_21.setText(_translate("Form", "RAKİP-1 Durum"))
        self.label_20.setText(_translate("Form", "RAKİP-2 Durum"))
        self.label_19.setText(_translate("Form", "RAKİP-3 Durum"))
        self.label_18.setText(_translate("Form", "RAKİP-4 Durum"))
        self.label_30.setText(_translate("Form", "RAKİP-5 Durum"))
        self.label_31.setText(_translate("Form", "RAKİP-6 Durum"))
        self.label_29.setText(_translate("Form", "RAKİP-7 Durum"))
        self.label_35.setText(_translate("Form", "RAKİP-8 Durum"))
        self.label_36.setText(_translate("Form", "RAKİP-9 Durum"))
        self.label_37.setText(_translate("Form", "RAKİP-10 Durum"))
        self.label_34.setText(_translate("Form", "RAKİP-11 Durum"))
        self.label_32.setText(_translate("Form", "RAKİP-13 Konum"))
        self.label_23.setText(_translate("Form", "RAKİP-14 Konum"))
        self.label_17.setText(_translate("Form", "RAKİP-15 Konum"))
        self.label_95.setText(_translate("Form", "RAKİP-16 Konum"))
        self.label_96.setText(_translate("Form", "RAKİP-17 Konum"))
        self.label_97.setText(_translate("Form", "RAKİP-18 Konum"))
        self.label_98.setText(_translate("Form", "RAKİP-19 Konum"))
        self.label_99.setText(_translate("Form", "RAKİP-20 Konum"))
        self.pushButton_4.setText(_translate("Form", "FBWA Mode"))
        self.pushButton_5.setText(_translate("Form", "LOİTER Mode"))
        self.label_49.setText(_translate("Form", "TextLabel_pitch"))
        self.label_50.setText(_translate("Form", "TextLabel_yaw"))
        self.label_51.setText(_translate("Form", "TextLabel_roll"))
        self.label_52.setText(_translate("Form", "TextLabel_voltaj"))
        self.label_53.setText(_translate("Form", "TextLabel_rssi"))
        self.label_54.setText(_translate("Form", "iHA PİTCH:"))
        self.label_55.setText(_translate("Form", "İHA YAW:"))
        self.label_56.setText(_translate("Form", "İHA ROLL:"))
        self.label_57.setText(_translate("Form", "BATARYA VOLTAJ:"))
        self.label_58.setText(_translate("Form", "RSSİ:"))
        self.pushButton_6.setText(_translate("Form", "RTL Mode"))
        self.label_60.setText(_translate("Form", "LAT"))
        self.label_24.setText(_translate("Form", "SAFDER KONUM_lat"))
        self.label_25.setText(_translate("Form", "RAKİP-1 Konum_lat"))
        self.label_26.setText(_translate("Form", "RAKİP-2 Konum_lat"))
        self.label_27.setText(_translate("Form", "RAKİP-3 Konum_lat"))
        self.label_28.setText(_translate("Form", "RAKİP-4 Konum_lat"))
        self.label_38.setText(_translate("Form", "RAKİP-5 Konum_lat"))
        self.label_39.setText(_translate("Form", "RAKİP-6 Konum_lat"))
        self.label_40.setText(_translate("Form", "RAKİP-7 Konum_lat"))
        self.label_41.setText(_translate("Form", "RAKİP-8 Konum_lat"))
        self.label_42.setText(_translate("Form", "RAKİP-9 Konum_lat"))
        self.label_43.setText(_translate("Form", "RAKİP-10 Konum_lat"))
        self.label_44.setText(_translate("Form", "RAKİP-11 Konum_lat"))
        self.label_45.setText(_translate("Form", "RAKİP-12 Konum_lat"))
        self.label_46.setText(_translate("Form", "RAKİP-13 Konum_lat"))
        self.label_47.setText(_translate("Form", "RAKİP-14 Konum_lat"))
        self.label_48.setText(_translate("Form", "RAKİP-15 Konum_lat"))
        self.label_100.setText(_translate("Form", "RAKİP-16 Konum_lat"))
        self.label_101.setText(_translate("Form", "RAKİP-17 Konum_lat"))
        self.label_102.setText(_translate("Form", "RAKİP-18 Konum_lat"))
        self.label_103.setText(_translate("Form", "RAKİP-19 Konum_lat"))
        self.label_104.setText(_translate("Form", "RAKİP-20 Konum_lat"))
        self.label_61.setText(_translate("Form", "LONG"))
        self.label_62.setText(_translate("Form", "SAFDER KONUM_long"))
        self.label_63.setText(_translate("Form", "RAKİP-1 Konum_long"))
        self.label_64.setText(_translate("Form", "RAKİP-2 Konum_long"))
        self.label_65.setText(_translate("Form", "RAKİP-3 Konum_long"))
        self.label_66.setText(_translate("Form", "RAKİP-4 Konum_long"))
        self.label_67.setText(_translate("Form", "RAKİP-5 Konum_long"))
        self.label_68.setText(_translate("Form", "RAKİP-6 Konum_long"))
        self.label_69.setText(_translate("Form", "RAKİP-7 Konum_long"))
        self.label_70.setText(_translate("Form", "RAKİP-8 Konum_long"))
        self.label_71.setText(_translate("Form", "RAKİP-9 Konum_long"))
        self.label_72.setText(_translate("Form", "RAKİP-10 Konum_long"))
        self.label_73.setText(_translate("Form", "RAKİP-11 Konum_long"))
        self.label_74.setText(_translate("Form", "RAKİP-12 Konum_long"))
        self.label_75.setText(_translate("Form", "RAKİP-13 Konum_long"))
        self.label_76.setText(_translate("Form", "RAKİP-14 Konum_long"))
        self.label_77.setText(_translate("Form", "RAKİP-15 Konum_long"))
        self.label_105.setText(_translate("Form", "RAKİP-16 Konum_long"))
        self.label_106.setText(_translate("Form", "RAKİP-17 Konum_long"))
        self.label_107.setText(_translate("Form", "RAKİP-18 Konum_long"))
        self.label_108.setText(_translate("Form", "RAKİP-19 Konum_long"))
        self.label_109.setText(_translate("Form", "RAKİP-20 Konum_long"))
        self.label_78.setText(_translate("Form", "YÜKSEKLİK"))
        self.label_79.setText(_translate("Form", "SAFDER KONUM_alt"))
        self.label_80.setText(_translate("Form", "RAKİP-1 Konum_alt"))
        self.label_81.setText(_translate("Form", "RAKİP-2 Konum_alt"))
        self.label_82.setText(_translate("Form", "RAKİP-3 Konum_alt"))
        self.label_83.setText(_translate("Form", "RAKİP-4 Konum_alt"))
        self.label_84.setText(_translate("Form", "RAKİP-5 Konum_alt"))
        self.label_85.setText(_translate("Form", "RAKİP-6 Konum_alt"))
        self.label_86.setText(_translate("Form", "RAKİP-7 Konum_alt"))
        self.label_87.setText(_translate("Form", "RAKİP-8 Konum_alt"))
        self.label_88.setText(_translate("Form", "RAKİP-9 Konum_alt"))
        self.label_89.setText(_translate("Form", "RAKİP-10 Konum_alt"))
        self.label_90.setText(_translate("Form", "RAKİP-11 Konum_alt"))
        self.label_91.setText(_translate("Form", "RAKİP-12 Konum_alt"))
        self.label_92.setText(_translate("Form", "RAKİP-13 Konum_alt"))
        self.label_93.setText(_translate("Form", "RAKİP-14 Konum_alt"))
        self.label_94.setText(_translate("Form", "RAKİP-15 Konum_alt"))
        self.label_110.setText(_translate("Form", "RAKİP-16 Konum_alt"))
        self.label_111.setText(_translate("Form", "RAKİP-17 Konum_alt"))
        self.label_112.setText(_translate("Form", "RAKİP-18 Konum_alt"))
        self.label_113.setText(_translate("Form", "RAKİP-19 Konum_alt"))
        self.label_114.setText(_translate("Form", "RAKİP-20 Konum_alt"))
    def uav_connect(self):
        global vehicle
        self.vehicle = connect('127.0.0.1:14550', wait_ready=True)

    def otonom_mode(self):
        vehicle.mode = VehicleMode('AUTO')
    def manuel_mode(self):
        vehicle.mode = VehicleMode('STABILIZE')
    def FBWA_mode(self): #1
        vehicle.mode = VehicleMode("FBWA")
    def RTL_mode(self):
        vehicle.mode = VehicleMode("RTL")
    def Loiter_mode(self):
        vehicle.mode = VehicleMode("LOITER")
if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    win = Ui_Form()
    win.setupUi(win)
    win.show()
    def update_label():
        global x,y, sol_ust_x, sol_ust_y, sol_alt_x, sol_alt_y,sag_ust_x,sag_ust_y,sag_alt_x,sag_alt_y,map_sol_ust_x,map_sol_ust_y,map_sol_alt_x,map_sol_alt_y,map_sag_ust_x,map_sag_ust_y,map_sag_alt_x,map_sag_alt_y
        global heading_bizim,heading1,heading2,heading3,heading4,heading5,heading6
        global en_kucuk_x,en_kucuk_y,en_kucuk_map_x,en_kucuk_map_y, en_buyuk_x, en_buyuk_y,en_buyuk_map_x,en_buyuk_map_y
        global x_vehicle,y_vehicle
        heading_bizim = vehicle.heading
        x = vehicle.location.global_frame.lat # x_vehicle
        y = vehicle.location.global_frame.lon # y_vehicle
        x_numpy = numpy.random.uniform(38.367536, 38.373399)
        y_numpy = numpy.random.uniform(27.196755, 27.20463)
        sol_ust_x = 41.517757
        sol_ust_y = 36.113688
        sol_alt_x = 41.506116
        sol_alt_y = 36.113742
        sag_ust_x = 41.517444
        sag_ust_y = 36.125748
        sag_alt_x = 41.505554
        sag_alt_y = 36.126703
        map_sol_ust_x = 900
        map_sol_ust_y = 80
        map_sol_alt_x = 900
        map_sol_alt_y = 970
        map_sag_ust_x = 1600
        map_sag_ust_y = 80
        map_sag_alt_x = 1600
        map_sag_alt_y = 970
        x_lists = [sol_ust_x, sol_alt_x, sag_ust_x, sag_alt_x]
        y_lists = [sol_ust_y, sol_alt_y, sag_ust_y, sag_alt_y]
        x_map_lists = [map_sol_ust_x, map_sol_alt_x, map_sag_ust_x, map_sag_alt_x]
        y_map_lists = [map_sol_ust_y, map_sol_alt_y, map_sag_ust_y, map_sag_alt_y]
        en_kucuk_x = sol_ust_x
        en_buyuk_x = sol_ust_x
        en_kucuk_y = sol_ust_y
        en_buyuk_y = sol_ust_y
        en_kucuk_map_x = map_sol_ust_x
        en_buyuk_map_x = map_sol_ust_x
        en_kucuk_map_y = map_sol_ust_y
        en_buyuk_map_y = map_sol_ust_x
        for i in x_lists:
            if (i < en_kucuk_x):
                en_kucuk_x = i
            if (i > en_buyuk_x):
                en_buyuk_x = i
        for i in y_lists:
            if (i < en_kucuk_y):
                en_kucuk_y = i
            if (i > en_buyuk_y):
                en_buyuk_y = i
        for i in x_map_lists:
            if (i < en_kucuk_map_x):
                en_kucuk_map_x = i
            if (i > en_buyuk_map_x):
                en_buyuk_map_x = i
        for i in y_map_lists:
            if (i < en_kucuk_map_y):
                en_kucuk_map_y = i
            if (i > en_buyuk_map_y):
                en_buyuk_map_y = i

        #SAFDER SETTEXLERİ
        win.label_14.setText(("Lat:"+str(vehicle.location.global_frame.lat)))
        win.label_15.setText(("Lon:"+str(vehicle.location.global_frame.lon))) #vehicle.location.global_frame.lon
        win.label_16.setText(str(vehicle.location.global_relative_frame.alt))
        win.label_13.setText(str(vehicle.groundspeed))
        win.label_12.setText(str(vehicle.mode))
        win.label_24.setText(str(x)) #Safder konumun yanı
        win.label_62.setText(str(y))
        win.label_79.setText(str(vehicle.location.global_relative_frame.alt)) #1
        win.label_49.setText(str(vehicle.attitude.pitch))
        win.label_50.setText(str(vehicle.attitude.yaw))
        win.label_51.setText(str(vehicle.attitude.roll))
        win.label_52.setText(str(vehicle.battery.voltage))

        #SUNUCU VERİSİ ALMA YERİ EN BÜYÜK VE ÖNEMLİ
        a = {'sunucusaati': {'gun': 10, 'saat': 8, 'dakika': 8, 'saniye': 28, 'milisaniye': 840}, 'konumBilgileri':
            [{'takim_numarasi': 1, 'iha_enlem': 41.5105362, 'iha_boylam': 36.118885, 'iha_irtifa': 97.609,
              'iha_dikilme': 0.464, 'iha_yonelme': 39.303, 'iha_yatis': 52.894, 'iha_hizi': 22.5511627,
              'zaman_farki': -41579476},
             {'takim_numarasi': 4, 'iha_enlem': 41.085083, 'iha_boylam': 28.9982147, 'iha_irtifa': 188.578,
              'iha_dikilme': -5.14558172, 'iha_yonelme': 304.197571, 'iha_yatis': -0.0280653648, 'iha_hizi': 12.2547474,
              'zaman_farki': -51218236},
             {'takim_numarasi': 8, 'iha_enlem': 40.7130127, 'iha_boylam': 30.0283928, 'iha_irtifa': 49.858,
              'iha_dikilme': 0.0, 'iha_yonelme': -100.0, 'iha_yatis': 58.0, 'iha_hizi': 25.0, 'zaman_farki': -56813556},
             {'takim_numarasi': 9, 'iha_enlem': 43.5765457, 'iha_boylam': 22.3854218, 'iha_irtifa': 100.0,
              'iha_dikilme': 5.0, 'iha_yonelme': 256.0, 'iha_yatis': 0.0, 'iha_hizi': 223.0, 'zaman_farki': -39174667},
             {'takim_numarasi': 14, 'iha_enlem': 43.5765457, 'iha_boylam': 22.3854218, 'iha_irtifa': 100.0,
              'iha_dikilme': 5.0, 'iha_yonelme': 256.0, 'iha_yatis': 0.0, 'iha_hizi': 223.0, 'zaman_farki': -39174667},
             {'takim_numarasi': 21, 'iha_enlem': 43.5765457, 'iha_boylam': 22.3854218, 'iha_irtifa': 100.0,
              'iha_dikilme': 5.0, 'iha_yonelme': 256.0, 'iha_yatis': 0.0, 'iha_hizi': 223.0, 'zaman_farki': -39174667},
             {'takim_numarasi': 23, 'iha_enlem': 41.512, 'iha_boylam': 36.12, 'iha_irtifa': 0.0, 'iha_dikilme': 14.0,
              'iha_yonelme': 0.0, 'iha_yatis': 25.0, 'iha_hizi': 15.0, 'zaman_farki': -11548367},
             {'takim_numarasi': 24, 'iha_enlem': 40.2318, 'iha_boylam': 29.0048828, 'iha_irtifa': 40.0,
              'iha_dikilme': 5.0, 'iha_yonelme': 256.0, 'iha_yatis': 10.0, 'iha_hizi': 15.0, 'zaman_farki': -45431724}]}
        # print(a['iha_enlem'])
        list_enlem = []
        list_boylam = []
        list_irtifa = []
        list_yonelme = []
        i = 0
        while i < 20:
            try:
                print(a['konumBilgileri'][i]['iha_enlem'], a['konumBilgileri'][i]['iha_boylam'])
                takim_enlem = a['konumBilgileri'][i]['iha_enlem']
                takim_boylam = a['konumBilgileri'][i]['iha_boylam']
                takim_irtifa = a['konumBilgileri'][i]['iha_irtifa']
                takim_yonelme = a['konumBilgileri'][i]['iha_yonelme']
                list_enlem.append(takim_enlem)
                list_boylam.append(takim_boylam)
                list_irtifa.append(takim_irtifa)
                list_yonelme.append(takim_yonelme)
                i += 1
            except:
                print("takım bitti")
                print("i",i)
                #LİSTE BİTTİ VE TEXTLERİ GÜNCELLEME
                win.label_25.setText(str(list_enlem[0]))
                win.label_63.setText(str(list_boylam[0]))
                win.label_80.setText(str(list_irtifa[0]))
                heading1 = list_yonelme[0]
                win.label_26.setText(str(list_enlem[1]))
                win.label_64.setText(str(list_boylam[1]))
                win.label_81.setText(str(list_irtifa[1]))
                heading2 = list_yonelme[1]
                win.label_27.setText(str(list_enlem[2]))
                win.label_65.setText(str(list_boylam[2]))
                win.label_82.setText(str(list_irtifa[2]))
                heading3 =  list_yonelme[2]
                win.label_28.setText(str(list_enlem[3]))
                win.label_66.setText(str(list_boylam[3]))
                win.label_83.setText(str(list_irtifa[3]))
                heading4 = list_yonelme[3]
                win.label_38.setText(str(list_enlem[4]))
                win.label_67.setText(str(list_boylam[4]))
                win.label_84.setText(str(list_irtifa[4]))
                win.label_39.setText(str(list_enlem[5]))
                win.label_68.setText(str(list_boylam[5]))
                win.label_85.setText(str(list_irtifa[5]))
                win.label_40.setText(str(list_enlem[6]))
                win.label_69.setText(str(list_boylam[6]))
                win.label_86.setText(str(list_irtifa[6]))
                heading6 = list_yonelme[6]
                win.label_41.setText(str(list_enlem[7]))
                win.label_70.setText(str(list_boylam[7]))
                win.label_87.setText(str(list_irtifa[7]))
                #try except yeri
                try:
                    win.label_42.setText(str(list_enlem[8]))
                    win.label_71.setText(str(list_boylam[8]))
                    win.label_88.setText(str(list_irtifa[8]))
                except:
                    print("liste bitti")

                try:
                    win.label_43.setText(str(list_enlem[9]))
                    win.label_72.setText(str(list_boylam[9]))
                    win.label_89.setText(str(list_irtifa[9]))
                except:
                    print("liste bitti")
                    rotate(list_enlem,list_boylam,list_irtifa,list_yonelme)

                i=0
            if i == 0:
                print("RESLENİYO")
                print(list_enlem)
                print(list_boylam)
                print(list_irtifa)
                print(list_yonelme)
                list_enlem.clear()
                list_boylam.clear()
                list_irtifa.clear()
                list_yonelme.clear()
                break

        win.label_22.setText(" SAFDER Bağlanıldı")
        win.label_21.setText("RAKİP-1 Durum")
        win.label_20.setText("RAKİP-2 Durum")
        win.label_19.setText("RAKİP-3 Durum")
        win.label_18.setText("RAKİP-4 Durum")
        win.label_30.setText("RAKİP-5 Durum")
        win.label_31.setText("RAKİP-6 Durum")
        win.label_29.setText("RAKİP-7 Durum")
        win.label_35.setText("RAKİP-8 Durum")
        win.label_36.setText("RAKİP-9 Durum")
        win.label_37.setText("RAKİP-10 Durum")
        win.label_34.setText("RAKİP-11 Durum")
        win.label_32.setText("RAKİP-13 Durum")
        win.label_23.setText("RAKİP-14 Durum")
        win.label_17.setText("RAKİP-15 Durum")
        win.label_95.setText("RAKİP-16 Durum")
        win.label_96.setText("RAKİP-17 Durum")
        win.label_97.setText("RAKİP-18 Durum")
        win.label_98.setText("RAKİP-19 Durum")
        win.label_99.setText("RAKİP-20 Durum")


        """
        win.label_26.setText((("Lat:" + str(x_rand2) + "-" + "Lon: " + str(y_rand2))))
        win.label_27.setText((("Lat:" + str(x_rand3) + "-" + "Lon:" + str(y_rand3))))
        win.label_25.setText((("Lat:" + str(x_rand4) + "-" + "Lon:" + str(y_rand4))))
        win.label_24.setText((("Lat:" + str(x_rand5) + "-" + "Lon:" + str(y_rand5)))) """

    def rotate(list_enlem,list_boylam,list_irtifa,list_yonelme):
        enlemler = []
        boylamlar = []
        print("ROTATE ATIYORUM")
        for i,j in zip(list_enlem,list_boylam):
                x_1 = en_buyuk_x - i
                oran_x = (en_buyuk_map_x - en_kucuk_map_x) / (en_buyuk_x - en_kucuk_x)
                x_2 = x_1 * (oran_x)
                x_3 = en_kucuk_map_x + int(x_2)
                y_1 = en_buyuk_y - j
                oran_y = (en_buyuk_map_y - en_kucuk_map_y) / (en_buyuk_y - en_kucuk_y)
                y_2 = y_1 * (oran_y)
                y_3 = en_kucuk_map_y + int(y_2)
                enlemler.append(x_3)
                boylamlar.append(y_3)

        x_1 = en_buyuk_x - x
        oran_x = (en_buyuk_map_x - en_kucuk_map_x) / (en_buyuk_x - en_kucuk_x)
        x_2 = x_1 * (oran_x)
        x_3 = en_kucuk_map_x + int(x_2)
        y_1 = en_buyuk_y - y
        oran_y = (en_buyuk_map_y - en_kucuk_map_y) / (en_buyuk_y - en_kucuk_y)
        y_2 = y_1 * (oran_y)
        y_3 = en_kucuk_map_y + int(y_2)
        win.pixmap3 = QtGui.QPixmap(
            "/home/ege/Downloads/uçak.png")
        win.pixmap2 = QtGui.QPixmap(
            "/home/ege/Downloads/uav_bizim2.png")  #BİZİM UÇAK
        win.pixmap = QtGui.QPixmap("/home/ege/Downloads/airliner.png") #RAKİP UÇAKLAR
        # image for your label
        print("UÇAK ŞUAN BURADA {},{}".format(x_3,y_3))
        pixmap_rotated_bizim = win.pixmap2.transformed(QTransform().rotate(90), QtCore.Qt.SmoothTransformation)
        pixmap_rotated = win.pixmap.transformed(QTransform().rotate(heading1), QtCore.Qt.SmoothTransformation)
        pixmap_rotated2 = win.pixmap.transformed(QTransform().rotate(heading2), QtCore.Qt.SmoothTransformation)
        pixmap_rotated3 = win.pixmap.transformed(QTransform().rotate(heading3), QtCore.Qt.SmoothTransformation)
        pixmap_rotated4 = win.pixmap.transformed(QTransform().rotate(heading4), QtCore.Qt.SmoothTransformation)
        pixmap_rotated6 = win.pixmap.transformed(QTransform().rotate(heading6), QtCore.Qt.SmoothTransformation)
        """
        win.label_3.setGeometry(QtCore.QRect(x_rand2_4, y_rand2_4, 461, 691)) #SON İKİ BASAMAK HEİGHT AND WEİGHT
        win.label_4.setGeometry(QtCore.QRect(x_rand3_4, y_rand3_4, 461, 691))
        win.label_5.setGeometry(QtCore.QRect(x_rand4_4, y_rand4_4, 461, 691))
        win.label_6.setGeometry(QtCore.QRect(x_rand5_4, y_rand5_4, 461, 691))"""
        win.label_120.setGeometry(QtCore.QRect(enlemler[6],boylamlar[6], 21,16))
        print("enlemler",enlemler)
        print("boylamlar",boylamlar)
        enlemler.clear()
        boylamlar.clear()
        win.label_6.setPixmap(pixmap_rotated)
        win.label_4.setPixmap(pixmap_rotated2)
        win.label_2.setPixmap(pixmap_rotated3)
        win.label_3.setPixmap(pixmap_rotated4)
        win.label_5.setPixmap(pixmap_rotated_bizim)  # LABEL 5 BİZİM UAV WİN.PİXMAP2 BİZİM UAV


    timer = QtCore.QTimer()
    timer.timeout.connect(update_label)
    #timer.timeout.connect(rotate)
    timer.start(1000)  # every 10,000 millisecond
    sys.exit(app.exec())


